name: Tests

on: [pull_request, push]
env:
    AWS_ACCESS_KEY: ${{ secrets.AWS_KEY_ID }}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET }}
    BOT_ID: P76TEI6VLR
    BOT_ALIAS_ID: TSTALIASID
    AWS_REGION: us-east-1
    LOCALE_ID: en_GB

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn
            - name: Run tests
              run: yarn test